services:
  python-producer:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./apps/producer-python:/app
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    command: >
      sh -c "
        pip install poetry &&
        poetry config virtualenvs.create false &&
        poetry install &&
        poetry run python main.py
      "
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  worker-go:
    build:
      context: ./apps/worker_go
    container_name: worker_go
    working_dir: /app
    volumes:
      - ./apps/worker_go:/app    # <<< HOT RELOAD
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - python-producer
      - nest-dev
    restart: unless-stopped
  nest-dev:
    build:
      context: ./apps/api
    container_name: nest-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/app                     
    env_file:
      - .env
    environment:
      - CI=true
      - PMPM_HOME=/app/.pnpm-store
    command: sh -c "
      pnpm install --force &&
      pnpm start:dev"
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
  frontend:
    build:
      context: ./apps/frontend
    container_name: frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://nest-dev:3000
    depends_on:
      - nest-dev
    restart: unless-stopped
volumes:
  mongo_data: