
FROM golang:1.25-alpine AS builder 

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker-go ./cmd/worker/

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/worker-go .

CMD ["./worker-go"]
