apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: production
spec:
  type: NodePort # Considerar LoadBalancer ou Ingress para produção
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000