apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      # InitContainer: aguarda o MongoDB estar pronto
      initContainers:
      - name: wait-for-mongo
        image: mongo:7
        command:
          - sh
          - -c
          - |
            echo "Aguardando MongoDB aceitar conexões autenticadas..."
            until mongosh --host mongo-service --port 27017 -u root -p root --authenticationDatabase admin --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
              echo "MongoDB ainda não está pronto. Tentando novamente em 3 segundos..."
              sleep 3
            done
            echo "MongoDB está pronto! Iniciando API..."


      containers:
        - name: api
          image: prfs/api-nest:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: PORT

            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: MONGO_URI

            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: RABBITMQ_URL

            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_ACCESS_SECRET

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_REFRESH_SECRET
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: GEMINI_API_KEY
          # Liveness: verifica se a API está respondendo
