FROM python:3.11

WORKDIR /app

RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root --no-interaction --no-ansi
COPY . .

CMD ["poetry", "run", "python", "main.py"]