apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: mongodb
  namespace: production
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/db
    type: DirectoryOrCreate
