FROM node:22-alpine

WORKDIR /app

RUN mkdir -p /app && chmod -R 777 /app
RUN npm install -g pnpm
RUN mkdir -p /app/.pnpm-store && chmod -R 777 /app/.pnpm-store

ENV PNPM_HOME=/app/.pnpm-store
ENV PATH=$PNPM_HOME:$PATH

# Copiar package.json da pasta apps/api
COPY package.json ./

RUN pnpm install

# Copiar todo o código da API
COPY . .

EXPOSE 3000

RUN ln -s /app/node_modules /app/node_modules || true

CMD ["pnpm", "start"]

